name: flutter_dev_packages
description: This plugin includes components, utilities, and more to make it easier to develop the Flutter app.
version: 1.0.0
homepage: https://github.com/Dev-hwang/flutter_dev_packages

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.3
  device_info_plus: ^3.2.4
  flutter_local_notifications: ^9.6.1
  fluttertoast: ^8.0.9
  http: ^0.13.4
  intl: ^0.17.0
  sqflite: ^2.0.2
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.15
  sentry: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.flutter_dev_packages
        pluginClass: FlutterDevPackagesPlugin
      ios:
        pluginClass: FlutterDevPackagesPlugin
